#!/usr/bin/env python3
"""S0 of ruling 035: read the archive back, and record what it does not hold.

The 034 writer did

    arrays[f"n{n}_reference"] = r.pop("vectors")["reference"]

which pops the dictionary holding BOTH vectors and keeps only the reference
member. The estimated vectors and the signed residuals were never written. The
keys are inspected here rather than assumed, and the missing arrays are
regenerated by S1/S2 from cached inputs -- reprocessing, not a new physical
run.

Zero physical queries.
"""
from __future__ import annotations

import hashlib
import json
import subprocess
import sys
import time
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[2]
REV = ROOT / "artifacts" / "revisions" / "mahakal_v4_1"
P034 = sorted(REV.glob("P034_*"))[-1] if list(REV.glob("P034_*")) else None
N033B = REV / "N033B_20260907T211922Z_45bd28e"
HULL = REV / "G1C_20260907T075203Z_d252697" / "CLOSEOUT_ARRAYS_029.npz"
HELPER = ROOT / ("docs/revisions/mahakal_v4_1/review035/"
                 "cancellation_and_templates_035.py")


def sha(p: Path) -> str:
    h = hashlib.sha256()
    with Path(p).open("rb") as f:
        for c in iter(lambda: f.read(1 << 20), b""):
            h.update(c)
    return h.hexdigest()


OVERLAY = """# INTERPRETATION_OVERLAY_035

Ruling: PAPER_I_CANCELLATION_RULING_035
Reviewed commit: 67f3523c33d21468ad962a7fe19cd806ad76e53b

Additive. No file written under rulings 029-034 is edited and every earlier
token stands.

## 1. The 10x-to-57x gap was not pure cancellation

The 034 report divided a per-node aggregate by the largest measured channel
error and called the ratio conservatism from cancellation. It is not one
effect. Writing K = W O and delta_c for one channel's node discrepancies,

    E_c = ||K delta_c||        the actual signed detector residual
    A_c = ||K |delta_c| ||     cancellation removed inside each pixel only
    T_c = sum_p ||K[:,p]|| |delta_pc|    detector structure replaced by a sum
    U   = sum_p ||K[:,p]|| max_c |delta_pc|   the 034 aggregate

with E <= A <= T <= U. The 034 figure was U against max_c E_c, so it mixed
three separate reductions: channel aggregation (U over T), loss of the
detector vector structure (T over A), and sign cancellation (A over E). The
reviewer's counterexample settles the point: 324 positive contributions in 324
distinct pixels give T/E = 18 with A/E = 1 and no cancellation anywhere.

S1 measures all four quantities per channel, each against its own reference
norm. The 034 scenario used the largest reference norm across channels, which
is not the same as meeting every channel's relative requirement.

## 2. A tighter bound cannot reduce a measured discrepancy

The measured signed residuals -- 9.594e-03, 4.274e-02 and 5.116e-01 relative,
at orders 0, 1 and 2, against a 5e-4 budget -- already contain whatever
cancellation the comparison has. Removing conservatism from a bound changes
where refinement is spent. It does not make the unchanged approximation more
accurate, and nothing in this stage is allowed to present it as if it did.

## 3. The 308,656 figure

It is an ORACLE_ZERO_HEAD_CACHED_DEFECT scenario: it assumes refining a
selected node drives its discrepancy to exactly zero while every other
contribution and weight stays put. Four child evaluations establish no such
thing. It is not a sufficient physical sampling budget and is relabelled
accordingly.

Greedy refinement also has a trap the 034 report did not state: contributions
of 1 and -0.99 sum to 0.01, and perfectly correcting the first leaves -0.99.
A local improvement can raise a signed global residual by breaking
cancellation.

## 4. Two scope corrections

**The same-leg flag.** "No order-2 stencil passes" means none passed a
declared heuristic -- source radius spanning under a quarter of its own mean
across the coarse cell. That is a smoothness proxy, not a geodesic branch
test, and large variation can coexist with exact interpolation of a simple
field. The span statistics stand; physical branch membership stays unverified
where the archived metadata does not establish it.

**The zero screen residual.** It is an equal-input consistency control, not an
absolute geometry validation. Both sides receive identical screen fields
through the same overlap operator, so a shared geometry error would cancel
there too. It does not reopen the separately accepted geometry tests; it just
does not stand in for them.

## 5. The export defect

The 034 response writer saved only the reference vectors. The estimated
vectors and the signed residuals were popped and discarded. The archive keys
are inspected in the manifest beside this file, and the missing arrays are
regenerated from cached inputs into a new directory. No physical evaluation is
repeated; the old directory is left byte-identical.

## 6. What the missing support still is

The order-2 comparison covers 62.8% of the fine-centre-labelled emitting area,
leaving about 0.6092 M^2 with no response bound of any kind. No cancellation
argument on the compared subset says anything about that region.
"""


def main(out: Path) -> int:
    t0 = time.time()
    out.mkdir(parents=True, exist_ok=False)
    keys = {}
    if P034 is not None:
        f = P034 / "CACHED_COMPOSITE_RESPONSE_034.npz"
        if f.is_file():
            with np.load(f, allow_pickle=False) as z:
                keys = {k: {"shape": list(z[k].shape), "dtype": str(z[k].dtype)}
                        for k in z.files}
    required = ["reference_vectors", "baseline_vectors", "candidate_vectors",
                "signed_residual_vectors", "channel_labels_and_times",
                "supported_node_ids_and_coordinates", "template_arrays",
                "CSR_overlap_data_indices_indptr_shape",
                "reference_norms_and_bound_hierarchy",
                "omitted_node_and_area_masks"]
    inputs = {}
    for p in [HULL, HELPER,
              N033B / "COMPARATOR_CAUSE_AND_CONFIRMATION_033.json"]:
        if p.is_file():
            inputs[str(p.relative_to(ROOT))] = sha(p)
    if P034 is not None:
        for p in sorted(P034.iterdir()):
            if p.is_file():
                inputs[str(p.relative_to(ROOT))] = sha(p)
    for n in (0, 1, 2):
        for prof in ("core", "fine"):
            f = ROOT / f"artifacts/raymaps/a050_i050_n{n}_{prof}.h5"
            if f.is_file():
                inputs[str(f.relative_to(ROOT))] = sha(f)
    man = {
        "stage": "S0", "ruling": "PAPER_I_CANCELLATION_RULING_035",
        "generated_utc": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
        "commit": subprocess.run(["git", "rev-parse", "HEAD"], cwd=ROOT,
                                 capture_output=True, text=True).stdout.strip(),
        "new_rays": 0, "physical_path_integrals": 0, "hull_root_solves": 0,
        "prior_run_directory": str(P034.relative_to(ROOT)) if P034 else None,
        "actual_034_npz_keys": keys,
        "estimated_vectors_present_in_034": any(
            "estimated" in k or "candidate" in k for k in keys),
        "export_defect": {
            "line": 'arrays[f"n{n}_reference"] = r.pop("vectors")["reference"]',
            "effect": "the dictionary holding both vectors is popped and only "
                      "its reference member is stored; the estimated vectors "
                      "and signed residuals were never written",
            "repair": "regenerate from cached inputs into a new directory; "
                      "the 034 directory is left byte-identical",
        },
        "required_arrays_for_this_ruling": required,
        "cached_inputs": inputs,
        "missing_inputs": [],
    }
    (out / "DETECTOR_TEMPLATE_035_INPUT_MANIFEST.json").write_text(
        json.dumps(man, indent=2) + "\n")
    (out / "INTERPRETATION_OVERLAY_035.md").write_text(OVERLAY)
    print(json.dumps({"stage": "S0", "out": str(out.relative_to(ROOT)),
                      "npz_keys": sorted(keys),
                      "estimated_present": man[
                          "estimated_vectors_present_in_034"],
                      "seconds": round(time.time() - t0, 1)}))
    return 0


if __name__ == "__main__":
    raise SystemExit(main((ROOT / sys.argv[1]).resolve()))
